### PR TITLE
Add regression test

### PR DESCRIPTION
**Pull request by sheerun**
Hello,

I'm adding a regression test that should output "false" but returns "true:
https://imgur.com/a/dykp264

I don't really know how to fix it so I'd rather leave it for you to fix...

Please not that current turf also has this issue and breaks for some polygons for me (e.g. for mask or intersect functions).

Here's original case that also breaks for me (part of border of Rzeszów city in Poland):

```
{  
   "type":"Feature",
   "properties":{  

   },
   "geometry":{  
      "type":"Polygon",
      "coordinates":[  
         [  

            [  
               21.938,
               50
            ],
            [  
               21.934727,
               50
            ],
            [  
               21.936414,
               49.998562
            ],
            [  
               21.935111,
               49.99912
            ],
            [  
               21.939748,
               49.997151
            ],
            [  
               21.938,
               50
            ]
         ]
      ]
   }
}
```

### CODE REVIEW

**Comment by rowanwins** [comment]
HI @sheerun - thanks for the test case, I'll do some digging and report back.

**Comment by rowanwins** [comment]
Hi @sheerun ,

I've just pushed v0.0.3 to npm which resolves this issue.

**Comment by sheerun** [comment]
Thank you :) Could you also fix this in newest turf if possible? If I pass such polygon to most turf functions, it fails with with something like Error: Self-intersecting, crossing input ring found at [21.93641249795278, 49.99856734753741]

**Comment by sheerun** [comment]
Here's border that turf breaks on: 

```
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[22.015316,49.974349],[22.016476,49.974391],[22.023223,49.972323],[22.028145,49.973461],[22.029351,49.971714],[22.033849,49.970626],[22.038672,49.978053],[22.042145,49.988553],[22.040801,49.990226],[22.038487,49.987504],[22.037027,49.987908],[22.031692,49.99195],[22.038231,49.996653],[22.043242,50.003551],[22.060094,50.009703],[22.065975,50.008578],[22.06977,50.002196],[22.066417,49.997374],[22.07282,49.998035],[22.081535,49.994185],[22.083651,49.996039],[22.082958,49.998884],[22.084873,50.006466],[22.082538,50.00774],[22.092796,50.010376],[22.09373,50.015315],[22.086162,50.024527],[22.075042,50.0347],[22.070506,50.033194],[22.067984,50.037295],[22.064093,50.038448],[22.063464,50.040515],[22.058857,50.04133],[22.057739,50.044753],[22.053482,50.048596],[22.0561,50.051957],[22.070952,50.05789],[22.069874,50.060247],[22.076925,50.067258],[22.076811,50.069108],[22.071719,50.068338],[22.069118,50.066301],[22.066452,50.067517],[22.066724,50.071846],[22.070735,50.07168],[22.070249,50.075126],[22.058951,50.072419],[22.055026,50.073653],[22.055084,50.070017],[22.052361,50.0709],[22.052082,50.068865],[22.051083,50.07149],[22.048491,50.069214],[22.04837,50.071245],[22.044522,50.071162],[22.045083,50.069763],[22.043171,50.068933],[22.041983,50.070235],[22.038066,50.069683],[22.041248,50.067574],[22.019178,50.075222],[22.005291,50.074908],[22.001291,50.075614],[22.00145,50.078319],[21.992922,50.078127],[21.990835,50.077982],[21.989938,50.074554],[21.984973,50.069911],[21.985243,50.066974],[21.976234,50.074071],[21.974049,50.072953],[21.951911,50.077001],[21.934549,50.072103],[21.932053,50.066703],[21.932913,50.061436],[21.923129,50.056633],[21.912744,50.056858],[21.897235,50.054667],[21.888953,50.055683],[21.883235,50.051718],[21.885133,50.050292],[21.868073,50.048076],[21.858695,50.04271],[21.868983,50.035249],[21.88096,50.034507],[21.901578,50.036922],[21.910057,50.030893],[21.917418,50.028736],[21.92232,50.028325],[21.936186,50.032325],[21.948536,50.02861],[21.944492,50.027032],[21.93872,50.019049],[21.938643,50.009787],[21.934727,50.004568],[21.936414,49.998562],[21.935111,49.99912],[21.939748,49.997151],[21.947705,49.998512],[21.949746,49.995109],[21.965415,49.992004],[21.962872,49.987338],[21.955535,49.984348],[21.955544,49.980864],[21.958894,49.976152],[21.955266,49.973666],[21.959075,49.968082],[21.958398,49.957189],[21.968596,49.947885],[21.968974,49.943639],[21.974147,49.934588],[21.98194,49.932581],[21.983256,49.933451],[21.979866,49.936471],[21.989883,49.939767],[21.992713,49.946489],[21.995223,49.962986],[22.019552,49.96344],[22.021992,49.965127],[22.022382,49.969623],[22.018271,49.97087],[22.017345,49.973143],[22.014197,49.973158],[22.015316,49.974349]]]}}
```

**Pull request merged**
